### ISSUE TITLE
02 - HelloWorld2  to work after Refactor > Convert to Objective-C ARC...

### ISSUE THREAD

**Issue by jamad** [erica/iphone-3.0-cookbook-#18]
I am trying to create the new project from scratch referring to 02-HelloWorld2 sample.

Because '@autoreleasepool' is used instead of 'NSAutoreleasePool' lately,
I tried to convert the sample to see how it works.
Actually, the build was finished with 'No issues' but the screen looks black screen.
Then I checked the debug output to find the following message.

"Applications are expected to have a root view controller at the end of application launch"

What should it be arranged to work like before refactor?

Cheers.

**Comment by erica** [comment]
See the 05 cookbook samples  (same place, new repository) -- E

**Comment by jamad** [comment]
I could not find the solution in the book iPhone 3.0 SDK. 
Do you mean the sample in the chapter 5 Working with View Controllers?
I need to know which page you meant by "(same place, new repository)".

**Comment by erica** [comment]
Same place (github.com/erica)
New repository (ios 5 cookbook)

-- E

**Comment by jamad** [comment]
Referring iOS-5-Cookbook > C05 > 01-Basic Menu,
I could solve the issue by moving UIWindow \* window declaration part from @implementation to @interface of Delegate.
Thanks for your hint.
